<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin page' => '',
    'Announce' => '',
    'Cancel' => '',
    'Changed date' => '',
    'Cities' => '',
    'City' => '',
    'Create' => '',
    'Create City' => '',
    'Create Region' => '',
    'Create Tour' => '',
    'Create Tour type' => '',
    'Create city' => '',
    'Create news item' => '',
    'Create region' => '',
    'Create tour' => '',
    'Create tour type' => '',
    'Created date' => '',
    'Dashboard' => '',
    'Description' => '',
    'Foreign tour' => '',
    'Get started' => '',
    'Id' => '',
    'Image' => '',
    'LABELS' => '',
    'Language' => '',
    'MAIN NAVIGATION' => '',
    'Name' => '',
    'News' => '',
    'Parent' => '',
    'Profile' => '',
    'Region' => '',
    'Regions' => '',
    'Sign out' => '',
    'Site content' => '',
    'Status' => '',
    'Title' => '',
    'Toggle navigation' => '',
    'Tour type' => '',
    'Tour types' => '',
    'Tours' => '',
    'Type' => '',
    'Update' => '',
    'Update city: ' => '',
    'Update news item: ' => '',
    'Update region: ' => '',
    'Update tour type: ' => '',
    'Update tour: ' => '',
    'User Image' => '',
    'View cities' => '',
    'Welcome' => '',
    'not published' => '',
    'published' => '',
];
