<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create city' => 'Создать город',
    'Create region' => 'Создать страну',
    'Create tour' => 'Создать тур',
    'Create tour type' => 'Создать вид туров',
    'Update city: ' => 'Обновить город: ',
    'Update region: ' => 'Обновить страну: ',
    'Update tour type: ' => 'Обновить вид туров: ',
    'Update tour: ' => 'Обновить тур: ',
    'Admin page' => 'Административная панель',
    'Announce' => 'Анонс',
    'Cancel' => 'Отмена',
    'Changed date' => 'Дата изменения',
    'Cities' => 'Города',
    'City' => 'Город',
    'Create' => 'Создать',
    'Create City' => 'Создать город',
    'Create Region' => 'Создать страну',
    'Create Tour' => 'Создать тур',
    'Create Tour type' => 'Создать вид туров',
    'Created date' => 'Дата создания',
    'Dashboard' => 'Администрирование',
    'Description' => 'Описание',
    'Foreign tour' => 'Забугор-вояж',
    'Get started' => 'Поехали!',
    'Id' => 'Номер',
    'Image' => 'Картинка',
    'LABELS' => 'Метки',
    'Language' => 'Язык',
    'MAIN NAVIGATION' => 'Навигация',
    'Name' => 'Имя',
    'Parent' => 'Родитель',
    'Profile' => 'Профиль',
    'Region' => 'Регион',
    'Regions' => 'Регионы',
    'Sign out' => 'Выход',
    'Site content' => 'Контент сайта',
    'Status' => 'Статус',
    'Title' => 'Название',
    'Toggle navigation' => 'Показать/скрыть навигацию',
    'Tour type' => 'Вид тура',
    'Tour types' => 'Виды туров',
    'Tours' => 'Туры',
    'Type' => 'Тип',
    'Update' => 'Обновить',
    'User Image' => 'Фото',
    'View cities' => 'Показать города',
    'Welcome' => 'Добро пожаловать',
    'not published' => 'не опубликован',
    'published' => 'опубликован',
];
